name: Testing CI pipeline
on:
  pull_request:
paths:
  - config/**
  - training/**
  - application/**
  - .github/workflows/test_code.yaml
jobs:
  test_model:
    name: Test new model
    runs_on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
      - name: Environment setup
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
        cache: pip
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/dev-requirements.txt')}}
          restore-keys: ${{ runner.os }}-pip-
      - name: Install packages
        run: pip install -r dev-requirements.txt
      - name: Pull data
        run: . . . . # Code to pull the required data.
      - name: Run training tests
        run: pytest training/tests
      - name: Save model
        run: python application/src/save_model.py
      - name: Serve the app locally and run app tests
        run: |
          bentoml serve ./application/src/create_service.py:service & sleep 10
          pytest application/tests
          kill -9 `lsof -i:3000 -t` # kill the app